---
new_page_extension: md
auto_deploy: false
admin_path: "/static/admin"
webhook_url: 
sections:
- type: directory
  path: projects
  label: Projects
  create: documents
  match: "**/*"
  templates:
  - project
- type: directory
  path: products
  label: Products
  create: documents
  match: "**/*"
  templates:
  - product
- type: directory
  path: team
  label: Team
  create: documents
  match: "**/*"
  templates:
  - team-member
- type: document
  path: data/theme.json
  label: Theme config
- type: heading
  label: Pages
- type: document
  path: data/homepage.json
  label: Homepage
- type: document
  path: data/project-page.json
  label: Project page
- type: document
  path: data/product-page.json
  label: Product page
- type: document
  path: data/contact-page.json
  label: Contact page
upload_dir: uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
instant_preview: 
build:
  preview_output_directory: dist
  preview_docker_image: forestryio/build:latest
  mount_path: "/opt/buildhome/repo"
  instant_preview_command: vuepress dev -p 8080 -h 0.0.0.0
  publish_command: gridsome build
  output_directory: dist
  preview_command: gridsome build
