---
new_page_extension: md
auto_deploy: false
admin_path: "/static/admin"
webhook_url: 
sections:
- type: directory
  path: projects
  label: Projects
  create: documents
  match: "**/*"
  templates:
  - project
- type: directory
  path: products
  label: Products
  create: documents
  match: "**/*"
  templates:
  - product
- type: document
  path: data/theme.json
  label: Theme config
- type: heading
  label: Pages
- type: document
  path: data/homepage.json
  label: Homepage
- type: document
  path: data/projectPage.json
  label: Project page
- type: document
  path: data/productPage.json
  label: Products page
- type: document
  path: data/contactPage.json
  label: Contact page
upload_dir: uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_command: gridsome build
  publish_command: gridsome build
  preview_output_directory: ".vuepress/dist"
  output_directory: dist
