---
label: Product
hide_body: false
fields:
- type: include
  name: product
  label: Product
  template: project
pages:
- products/suopis.md
- products/suopis-2.md
- products/spartan.md
- products/test.md
