---
label: Project
hide_body: false
fields:
- type: file
  name: thumbnail
  label: Thumbnail
  description: This will only show up on the front page
- type: boolean
  name: cover
  label: Stretch thumbnail
- type: text
  name: title
  label: Title
  config:
    required: true
- type: datetime
  name: date
  label: Date
  config:
    required: true
- type: tag_list
  name: categories
  label: Categories
  default:
  - none
  description: Required. Set first value to "none" to hide categories.
- type: color
  name: bg_color
  config:
    color_format: Hex
  label: Background color
- type: color
  name: fg_color
  config:
    color_format: Hex
  label: Foreground color
pages:
- projects/40-kg-daugiasraigtis-orlaivis.md
- projects/suopis-4.md
- projects/death-star.md
- projects/suopis-5.md
